server:
  port: 8081
spring:
  cloud:
    config:
      uri: http://localhost:8090/
      profile: development

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - refresh
  endpoint:
    health:
      show-details: always
health:
  config:
    enabled: true

#demo:
#  name: meteatbas
#  email: meteatbas@gmail.com
#  repositoryName: https://github.com/meteatbas/parcialSeven
#  filePath: //desktop-6ujvr85/Users/meteatbas/Documents/projectPartialSeven/
#  gitUsername: meteatbas
#  gitPassword: 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